### ISSUE TITLE
Any reason for not implementing as NB IT Connector instead?

### ISSUE THREAD

**Issue by rdelpeso** [tosbourn/Netbeans-Redmine-Integration#5]
I checked your plugin out since I'm interested on getting redmine integrated with NB. But I would like to know why you decided to not implement this as a connector?

In case you don't know about connectors:

Open the services window in NB, then right click issue trackers and select Create Issue Tracker. This new window has a connector dropdown.

Implementing as a connector would be in my opinion the perfect place for inserting redmine, since this integrates with every other feature of NB that currently supports Issue Tracker actions. Instead of re-inventing the wheel completely.

I'd like to help with this project so let me know what you think. Btw i have 0 java experience but i have 10 years of programming experience so i can get up to speed pretty fast :) . (visual basic, delphi, javascript, php, and a bit of c#)

**Comment by tosbourn** [comment]
Hey,

Sorry on the late reply - you are right, a connector would be the way forward.

When this was written Redmine didn't have the API it does now, so connectors wouldn't have worked - now it does so when I get time I will be re-writing this as a connector.
